### ISSUE TITLE
Perform configuration file sanity check every time

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ci-master#15]
Right now, if the "groups" configuration contains a repo that is not reflected in the "repositories" section, the command will crash.

e.g.
```
# cimas pull -f $CIMAS_CONFIG -r $CIMAS_WD -g samples
Pulling from mn-samples-iso...
Pulling from mn-samples-gb...
Pulling from mn-samples-mpf...
Error: undefined method `[]' for nil:NilClass
/Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cimas-0.1.0/lib/cimas/cli/command.rb:253:in `block in pull'
/Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cimas-0.1.0/lib/cimas/cli/command.rb:250:in `each'
```

The reason is `repo` is set to `nil` (`repo_by_name` can't find the repo), and `repo['branch']` crashes.

https://github.com/metanorma/cimas/blob/59d581b277411b6941c42418ed48b591368d86d0/lib/cimas/cli/command.rb#L252-L254

A startup configuration file check will prevent these errors.

In fact, the way to resolve this is to model Repository, Group and Settings separately as Ruby Classes and on parsing the configuration file, these errors can be detected.

**Comment by opoudjis** [comment]
Surfacing where this sits in the cimas/ci rehabilitation arc, leaving open as the work surface is genuinely live.

"Perform configuration file sanity check every time" maps cleanly onto two work items already named in the roadmap:

1. **Phase B cimas refactor** — [Phase B](https://github.com/metanorma/cimas/blob/main/plans/cimas-revival-and-release-workflow-realignment.md#phase-b--cimas-refactor-post-batch) explicitly calls for **YAML schemas for the cimas config files**: schemas for `cimas-config/cimas.yml`'s `repositories:` block (per-repo entries: `remote`, `branch`, `files:`, `template:`), the templates inheritance, the patches block (added in [#38](https://github.com/metanorma/cimas/pull/38)), and per-org config under `cimas-config/gh-actions/<org>/`. A schema-backed load IS the structural form of the "sanity check every time" this ticket proposes — the schema fails the load before any iteration runs, surfacing the config error in one place rather than hundreds of repo-iteration symptoms.

2. **[metanorma/ci#300](https://github.com/metanorma/ci/issues/300) Gap 3 — drift-audit subcommand** — Gap 3 implements a separate "diff classifier + heuristics + sync-blocking semantics" pass for detecting cimas-config-vs-real-state drift across the 187 repos. The sanity check at config-load (Phase B) catches structural / schema errors; the drift audit (Gap 3) catches state-divergence errors. Together they cover the "every time" surface this ticket asks for.

Implementation order: Phase B's schema scaffold first (defines where validation lives and what the schema language is), Gap 3's drift audit second (consumes the schema for repo-state validation).

Leaving open as an arc-resident item; will be picked up alongside the schema work in Phase B. If a specific class of config error you'd like to see caught at sanity-check time is concrete enough to spec now, that's worth flagging — the schema can be designed to catch it explicitly.

Refs the rehabilitation roadmap at [cimas-revival-and-release-workflow-realignment.md](https://github.com/metanorma/cimas/blob/main/plans/cimas-revival-and-release-workflow-realignment.md).

🤖

**Comment by opoudjis** [comment]
Closing as substantially delivered via the drift-audit tool loop shipped over 2026-07-03 → 2026-07-05:

- **[`metanorma/ci#335`](https://github.com/metanorma/ci/pull/335)** + **[`ci#338`](https://github.com/metanorma/ci/pull/338)** — initial drift-audit script + full 7-class detection (deleted / archived / transferred / branch drift / stale rationale / silent template drift / documented opt-out).
- **[`ci#341`](https://github.com/metanorma/ci/pull/341)** — scheduled workflow (weekly Wed 09:00 UTC, PAT for private-repo visibility, tracking-issue update).
- **[`ci#344`](https://github.com/metanorma/ci/pull/344)** — bundled fix for `read_template` path bug in the audit script.
- **[`ci#345`](https://github.com/metanorma/ci/pull/345)** — bundled fix for `.erb` templates being compared against raw (unrendered) source.
- **Rolling-report tracking issue: [`ci#342`](https://github.com/metanorma/ci/issues/342)** — auto-updated with every scheduled run.

The intent of this ticket — "cimas should validate its own config every time" — is now covered by a scheduled audit that catches every class of drift documented above, updates a visible rolling-report tracking issue, and no longer requires human triggering. The 2026-07-04 first-run report surfaced 242 legitimate silent-drift findings; the 2026-07-05 sweep + ci#347 course-correction addressed ~90% of them as pure template refresh, and follow-up cleanup waves will address the residual.

Leaving this closed with the arc-link record intact; opening a fresh ticket if a new class of drift emerges that the current 7-class taxonomy doesn't cover.

🤖
